pipeline {
    agent any

    environment {
        DOCKERHUB_CREDS=credentials('dockerhub-creds')
        LC_ALL = "en_US.UTF-8"
        LANG    = "en_US.UTF-8"
        LANGUAGE = "en_US.UTF-8"
    }


    stages {

        stage('Login'){
            steps{
                sh 'docker login -u $DOCKERHUB_CREDS_USR -p $DOCKERHUB_CREDS_PSW'
                }
            }


        stage('Pull image') {
            steps {
                sh 'docker pull anosov01/itmo_bigdata_lab2:latest'
            }
        }

        // stage("test PythonEnv") {
        //     steps {
        //         withPythonEnv('python3') {
        //             script {
        //                 sh 'pip install pytest'
        //             }
        //         }
        //     }
        // }

        stage('test PythonEnv') {
            steps {
                script {
                    // Set up Python environment
                    sh '''
                        python3 -m venv venv
                        . venv/bin/activate
                        pip install pytest
                    '''
                }
            }
        }

        stage('Run container') {
            steps {
                sh 'docker rm -v -f $(docker ps -qa) && docker compose up'
            }
        }
    }
    }

