pipeline {
    agent any

    environment {
        DOCKERHUB_CREDS=credentials('dockerhub-creds')
        LC_ALL = "en_US.UTF-8"
        LANG    = "en_US.UTF-8"
        LANGUAGE = "en_US.UTF-8"
    }

    stages {
        stage('Clone github repository') {
            steps {
                echo 'Cloning repo'
                sh 'curl https://ipecho.net/plain'
                sh 'ls'
                sh 'rm -r -f itmo_bigdata_lab4'
                git(
                    url: "git@github.com:alexej-anosov/itmo_bigdata_lab4.git",
                    branch: "main",
                    credentialsId: "alexej-key",
                    changelog: true,
                    poll: true
                )
				}
			}


        stage('Login'){
            steps{
                sh 'docker login -u $DOCKERHUB_CREDS_USR -p $DOCKERHUB_CREDS_PSW'
                }
            }

        stage('Build docker') {
            steps {
                dir("itmo_bigdata_lab4") {
                    sh 'docker compose build'
                } 
            }
        }

        stage('Push to DockerHub') {
            steps {
                dir("itmo_bigdata_lab4") {
                    sh 'docker push anosov01/itmo_bigdata_lab4:latest'
                }
            }
        }
    }

    post {
        always {
            dir("itmo_bigdata_lab4") {
                sh 'docker logout docker.io'
            }
        }
    }
}