pipeline {
    agent any

    environment {
        DOCKERHUB_CREDS=credentials('dockerhub-creds')
        LC_ALL = "en_US.UTF-8"
        LANG    = "en_US.UTF-8"
        LANGUAGE = "en_US.UTF-8"
    }

    options {
            timestamps()
            skipDefaultCheckout(true)
        }

    stages {
        stage('Clone github repository') {
            steps {
                echo 'Cloning repo'
                sh 'sudo rm -r -f itmo_bigdata_lab1'
                git(
                    url: "git@github.com:alexej-anosov/itmo_bigdata_lab1.git",
                    branch: "main",
                    credentialsId: "github-ssh-key",
                    changelog: true,
                    poll: true
                )
				}
			}


        stage('Login'){
            steps{
                sh 'docker login -u %DOCKERHUB_CREDS_USR% -p %DOCKERHUB_CREDS_PSW%'
                }
            }

        stage('Build docker') {
            steps {
                dir("itmo_bigdata_lab1") {
                    sh 'sudo docker compose build'
                }
            }
        }

        stage('Run docker') {
            steps {
                dir("itmo_bigdata_lab1") {
                    sh 'sudo docker compose up'
                }
            }
        }
        stage('Push to DockerHub') {
            steps {
                dir("itmo_bigdata_lab1") {
                    sh 'sudo docker push anosov01/itmo_bigdata_lab1:latest'
                }
            }
        }
    }

    post {
        always {
            dir("itmo_bigdata_lab1") {
                sh 'sudo docker compose down 2>null'
                sh 'sudo docker logout docker.io'
            }
        }
    }
}